version: '3.8' # Required for backward compatibility with older Docker Compose versions (pre-v1.27.0)
services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER_NM}
      POSTGRES_PASSWORD: ${DB_USER_PW}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    ports:
      - "8000:8080"
    environment:
      PIPELINE: ${PIPELINE}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      DB_NAME: ${DB_NAME}
      DB_USER_NM: ${DB_USER_NM}
      DB_USER_PW: ${DB_USER_PW}
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
      
  bot:
    build: .
    restart: always
    environment:
      PIPELINE: ${PIPELINE}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      DB_NAME: ${DB_NAME}
      DB_USER_NM: ${DB_USER_NM}
      DB_USER_PW: ${DB_USER_PW}
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runbot"

volumes:
  postgres_data: