# Generated by Django 5.1 on 2024-09-05 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_stage', models.CharField(choices=[('STATS', 'STATS'), ('ITEMS', 'ITEMS'), ('READY', 'READY'), ('FIGHT', 'FIGHT'), ('REWARD', 'REWARD')], default='STATS', max_length=6, verbose_name='Current stage')),
                ('hero_is_alive', models.BooleanField(default=True, verbose_name='Alive')),
                ('hero_class', models.CharField(default='Knight', max_length=20, verbose_name='Class')),
                ('nickname', models.CharField(default='Tough Tom', max_length=20, verbose_name='Name')),
                ('hero_str', models.SmallIntegerField(default=5, verbose_name='STR')),
                ('hero_agl', models.SmallIntegerField(default=5, verbose_name='AGL')),
                ('hero_int', models.SmallIntegerField(default=5, verbose_name='INT')),
                ('hero_free_stats', models.SmallIntegerField(default=3, verbose_name='FREE STATS')),
                ('hero_max_hp', models.SmallIntegerField(default=50, verbose_name='Max HP')),
                ('hero_max_ap', models.SmallIntegerField(default=50, verbose_name='Max AP')),
                ('hero_max_mp', models.SmallIntegerField(default=50, verbose_name='Max MP')),
                ('hero_cur_hp', models.SmallIntegerField(default=50, verbose_name='Current HP')),
                ('hero_cur_ap', models.SmallIntegerField(default=50, verbose_name='Current AP')),
                ('hero_cur_mp', models.SmallIntegerField(default=50, verbose_name='Current MP')),
                ('hero_armor', models.SmallIntegerField(default=0, verbose_name='Armor')),
                ('hero_magic_resist', models.SmallIntegerField(default=0, verbose_name='Magic Resistance')),
                ('hero_crit_resist', models.FloatField(default=0.0, verbose_name='Crit Resistance')),
                ('hero_pierce_resist', models.FloatField(default=0.0, verbose_name='Pierce Resistance')),
                ('hero_block_resist', models.FloatField(default=0.0, verbose_name='Block Resistance')),
                ('hero_react_resist', models.FloatField(default=0.0, verbose_name='React Resistance')),
                ('hero_dodge_resist', models.FloatField(default=0.0, verbose_name='Dodge Resistance')),
                ('hero_inventory', models.BooleanField(default=True)),
                ('exp_gained', models.PositiveIntegerField(default=0, verbose_name='Experience gained')),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
            },
        ),
        migrations.CreateModel(
            name='BattleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(verbose_name='Date started')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Finished')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Date finished')),
                ('current_round', models.PositiveSmallIntegerField(default=1, verbose_name='Current round')),
                ('total_rounds', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Total rounds')),
                ('hero_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_1', to='bot.heromodel', verbose_name='Hero 1')),
                ('hero_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_2', to='bot.heromodel', verbose_name='Hero 2')),
                ('hero_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_3', to='bot.heromodel', verbose_name='Hero 3')),
            ],
            options={
                'verbose_name': 'Battle',
                'verbose_name_plural': 'Battles',
            },
        ),
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.PositiveIntegerField(unique=True, verbose_name='Telegram account id')),
                ('level', models.PositiveSmallIntegerField(default=1, verbose_name='Level')),
                ('exp', models.PositiveBigIntegerField(default=0, verbose_name='Experience')),
                ('next_lvl_exp', models.PositiveBigIntegerField(default=300, verbose_name='Next Lvl Experience')),
                ('battles', models.PositiveIntegerField(default=0, verbose_name='Total battles')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='Wins')),
                ('deaths', models.PositiveIntegerField(default=0, verbose_name='Deaths')),
                ('draws', models.PositiveIntegerField(default=0, verbose_name='Draws')),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.heromodel', verbose_name='Current hero')),
            ],
            options={
                'verbose_name': "Player's tg account",
                'verbose_name_plural': "Players' tg accounts",
            },
        ),
        migrations.AddField(
            model_name='heromodel',
            name='hero_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tg_account', to='bot.playermodel', verbose_name='Player'),
        ),
        migrations.CreateModel(
            name='RoundModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Number')),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.battlemodel', verbose_name='Battle')),
            ],
            options={
                'verbose_name': 'Round',
                'verbose_name_plural': 'Rounds',
            },
        ),
        migrations.CreateModel(
            name='ActionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Number')),
                ('damage', models.SmallIntegerField(default=0, verbose_name='Damage')),
                ('heal', models.SmallIntegerField(default=0, verbose_name='Damage')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim', to='bot.heromodel', verbose_name='Object')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='bot.heromodel', verbose_name='Subject')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.roundmodel', verbose_name='Round')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
    ]
