# Generated by Django 5.1 on 2024-09-18 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlemodel',
            name='current_round',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Current round'),
        ),
        migrations.AlterField(
            model_name='battlemodel',
            name='hero_1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_1', to='bot.heromodel', verbose_name='Hero 1'),
        ),
        migrations.AlterField(
            model_name='battlemodel',
            name='hero_2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_2', to='bot.heromodel', verbose_name='Hero 2'),
        ),
        migrations.AlterField(
            model_name='battlemodel',
            name='hero_3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hero_3', to='bot.heromodel', verbose_name='Hero 3'),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='hero_class',
            field=models.CharField(default='Shaman', max_length=20, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='nickname',
            field=models.CharField(default='Holly Bob', max_length=20, verbose_name='Name'),
        ),
    ]
