# Generated by Django 5.1 on 2024-09-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_battlemodel_current_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlemodel',
            name='queue',
            field=models.BooleanField(default=True, verbose_name='Queued'),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='hero_class',
            field=models.CharField(default='Monk', max_length=20, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='nickname',
            field=models.CharField(default='Awesome Konstantin', max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='roundmodel',
            name='number',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number'),
        ),
    ]
