# Generated by Django 5.1 on 2024-09-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_heromodel_hero_class_alter_heromodel_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battlemodel',
            old_name='queue',
            new_name='queued',
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='hero_class',
            field=models.CharField(default='Paladin', max_length=20, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='nickname',
            field=models.CharField(default='Evil Karl', max_length=20, verbose_name='Name'),
        ),
    ]
