# Generated by Django 5.1 on 2024-09-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_rename_queue_battlemodel_queued_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlemodel',
            name='started',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date started'),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='hero_class',
            field=models.CharField(default='Monk', max_length=20, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='nickname',
            field=models.CharField(default='Sneaky Bill', max_length=20, verbose_name='Name'),
        ),
    ]
