# Generated by Django 5.1 on 2024-09-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_battlemodel_started_alter_heromodel_hero_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heromodel',
            name='hero_class',
            field=models.CharField(default='Necromancer', max_length=20, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='heromodel',
            name='nickname',
            field=models.CharField(default='Serious Rick', max_length=20, verbose_name='Name'),
        ),
    ]
