# Generated by Django 5.1 on 2024-09-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_heromodel_hero_class_alter_heromodel_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heromodel',
            old_name='nickname',
            new_name='hero_nickname',
        ),
    ]
