# Generated by Django 5.1 on 2024-09-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_rename_nickname_heromodel_hero_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heromodel',
            old_name='hero_nickname',
            new_name='nickname',
        ),
    ]
