# Generated by Django 5.1 on 2024-09-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_rename_hero_nickname_heromodel_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heromodel',
            name='hero_stage',
            field=models.CharField(choices=[('ENTER', 'ENTER'), ('STATS', 'STATS'), ('READY', 'READY'), ('FIGHT', 'FIGHT'), ('REWARD', 'REWARD')], default='ENTER', max_length=6, verbose_name='Current stage'),
        ),
    ]
